added pip list for checking

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,6 +39,13 @@ jobs:
           echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> $GITHUB_ENV
           echo "REDIRECT_URI=${REDIRECT_URI}" >> $GITHUB_ENV
 
+      - name: Verify Installed Packages and PATH
+        run: |
+          pip list
+          which black || echo "Black not found"
+          which flake8 || echo "Flake8 not found"
+          which pylint || echo "Pylint not found"
+
   jsdocs:
     runs-on: ubuntu-latest
     needs: setup
